### ISSUE TITLE
Unable to find meta filename location. Make sure you have installed LiveXAML into this project

### ISSUE THREAD

**Issue by ebicoglu** [OYIon/XamarinFormsLive#20]
I am getting the following error:

> Unable to find meta filename location. Make sure you have installed LiveXAML into this project

when i save a xaml file while the emulator is running the app.
I am using trial version (i got 11 days). 
my xaml files are located under the folder "views" in PCL project .

![livexaml-error](https://user-images.githubusercontent.com/9526587/31034684-cb36eec2-a56d-11e7-9ee8-ef271d70de54.jpg)

**Comment by ionoy** [comment]
Thanks for the quality report! I will try to replicate it today and report back.

**Comment by ionoy** [comment]
Couple of questions:

1) Why don't you use `Xamarin.Forms.2.4.0.*` with official NetStandard support?
2) Do you see `xamarinlive.meta` file in `obj/Debug/netstandard1.6` folder?

Thanks!

**Comment by ebicoglu** [comment]
hi

1. I updated to the latest Xamarin.Forms.
2. xamarinlive.meta file exists in ...\Shared\obj\Debug\netstandard1.6\xamarinlive.meta

**still not working!**
hovewer **i changed the output path and intermediate output path**. So the obj folder is not in the same folder with solution. To prevent too long file path problem in windows, i modified the csproj of like this

<OutputPath>C:\Project\Shared\bin\Debug\</OutputPath>
<IntermediateOutputPath>C:\Project\Shared\obj\Debug\</IntermediateOutputPath>

so if you expect them in the default paths you cannot find. check the csproj file...
this is my csproj of shared project:

```
<PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
    <PackageTargetFallback>$(PackageTargetFallback);dotnet5.6;portable-net45+win8</PackageTargetFallback>
    <RootNamespace>MyProject</RootNamespace>
    <AssemblyName>MyProject.Mobile.Shared</AssemblyName>	
	<UseShortFileNames>True</UseShortFileNames>    
	<OutputPath>C:\Project\Shared\bin\Debug\</OutputPath>
	<IntermediateOutputPath>C:\Project\Shared\obj\Debug\</IntermediateOutputPath>
  </PropertyGroup>
```
by the way can you clarify that which project should i reference livexaml dll (currently i am referencing to the shared project.)

**Comment by ionoy** [comment]
Good info. LiveXAML expects relative paths in `IntermediateOutputPath`, that's why it is failing to find the meta file. I will add a check for it.

**Comment by ebicoglu** [comment]
so ping me back when you've fixed.

**Comment by ionoy** [comment]
I've published the updated Visual Studio extension. It should be available shortly.

**Comment by ebicoglu** [comment]
updated the extension but still the same error. (xamarinlive.meta exists)

**Comment by ionoy** [comment]
Yeah, I've only tested it with old-style csproj. Visual Studio extension doesn't see added properties from the new project format. I need more time to investigate it.

I will extend your trial as soon as we get this fixed.

**Comment by ebicoglu** [comment]
ok. no problem.

**Comment by ebicoglu** [comment]
i saw extension is updated. but result is still same...

**Comment by ionoy** [comment]
Yeah, unfortunately, I haven't found the answer yet.

**Comment by ebicoglu** [comment]
Once you have found a solution I will test & buy it. ok?

**Comment by ionoy** [comment]
That would be great! But I still haven't found the answer. Probably should ask in MS GitHub issues.

**Comment by ebicoglu** [comment]
they are answering in github faster  than other platforms.

**Comment by ionoy** [comment]
I finally got an answer!

Can you try if the attached VSIX resolves the issue?

[LiveXAML.VisualStudio.zip](https://github.com/OYIon/LiveXAML/files/1382539/LiveXAML.VisualStudio.zip)

**Comment by ionoy** [comment]
By the way, I can extend your trial if you are still interested.

**Comment by ebicoglu** [comment]
hi, my trial expired. yes please extend my trial => alperonline [at] hotmail [dot] com

**Comment by ebicoglu** [comment]
alperonline [at] hotmail [dot] com

**Comment by ionoy** [comment]
Done!

**Comment by ebicoglu** [comment]
I've installed the extension you've just sent. But still says my license has expired. I tried pressing Copy Access button and Load License button but not works. Actually i didn't register to anywhere. I don't have a password  (I guess extension shouldn't be known my email address.) What should I do to start over a new trial license? 


![image](https://user-images.githubusercontent.com/9526587/31576168-5ff85ece-b0fe-11e7-89b4-27a1a0c1b075.png)

**Comment by ionoy** [comment]
Paste your email into `License email` and click Load license

**Comment by ebicoglu** [comment]
hi I've activated 12 days license. But still doesn't work. Same error message. If you need any logs contact me.  I've test with **Visual Studio 2017 v15.4.0.**

**Comment by ebicoglu** [comment]
hi I've activated 12 days license. But still doesn't work. Same error message. If you need any logs contact me.  I've test with **Visual Studio 2017 v15.4.0.**

**Comment by ionoy** [comment]
Can you send me your sample project?

Thanks!

**Comment by ebicoglu** [comment]
I'll try to make a simple version of the project. By the way my project is located at D:\Github\MyProject but DLL and OBJ folders are located at C:\Output\ . This may enlight you

**Comment by ionoy** [comment]
Hi again! Could you send me the sample project?

**Comment by ebicoglu** [comment]
Hi, sorry i couldn't have time to make a simple version of project. For me, giving you a log file is less tiring. If you can write logs to somewhere in my machine, i can send to you. So you can see where the problem is.

**Comment by ionoy** [comment]
You can just copy your project somewhere and delete all the sensitive information. I only need the one with the new csproj format. I will then try to reference it inside my sample application and see if it works. 

With the log, it would take a long back-and-forth communication to get to the issue.

**Comment by ionoy** [comment]
I was finally able to replicate the problem. Can you please try this new build?


[LiveXAML.VisualStudio.zip](https://github.com/OYIon/LiveXAML/files/1425342/LiveXAML.VisualStudio.zip)

EDIT: You can refresh your license, I have given you more trial time.

**Comment by ebicoglu** [comment]
hi Mihhail,

I've tested and finally it works 👍 
I'll test it deeply this week. 
Thanks

**Comment by ebicoglu** [comment]
hi
My trial has expired. Could you please extend my trial. I couldn't have time to try out the working version.
alperonline [@] hotmail.com

**Comment by ionoy** [comment]
Done
