### ISSUE TITLE
LiveXAML doesn't work with ContentPropertyAttribute

### ISSUE THREAD

**Issue by tomgilder** [OYIon/XamarinFormsLive#35]
We've got a custom page with a ContentPropertyAttribute set:

```
    [ContentProperty("InnerContent")]
    public partial class CustomContentPage : ContentPage
```

This makes LiveXAML blow up and not update when editing content in the child XAML.

See this repro project on iOS and Android: [LiveXAMLPageIssue.zip](https://github.com/OYIon/LiveXAML/files/1509563/LiveXAMLPageIssue.zip)

Tested on latest Visual Studio for Mac with LiveXAML extension v1.3.31 and NuGet package v1.3.14.

Cheers
Tom

**Comment by tomgilder** [comment]
Also doesn't work with NuGet package 2.0.18-beta

**Comment by ionoy** [comment]
Thanks! I'll take a look.

**Comment by ionoy** [comment]
I started investigating the issue. It seems like it's a bit more complicated than ignoring ContentPropertyAttribute. I'll get back to it on Friday, so it should be fixed by the end of the week.

Thanks for the feedback!

**Comment by ionoy** [comment]
Should be fixed in LiveXAML 2.1.1

**Comment by tomgilder** [comment]
I'm afraid I can't get my repro project to work with 2.1.1, it still doesn't update. Updating the text in `LiveXAMLPageIssuePage.xaml` causes the screen goes to blank.

LiveXAML NuGet 2.1.1 / Extension 1.3.31
VS for Mac 7.2.2
Xamarin.Forms 2.5.0.91635

**Comment by ionoy** [comment]
There were multiple issues with that one. But it should finally be fixed in LiveXAML 2.1.6.

**Comment by tomgilder** [comment]
Fantastic, thank you! Works perfectly.
